### ISSUE TITLE
Why not use qrc, and tried to use filesystem files?

### ISSUE THREAD

**Issue by lfdominguez** [kalaksi/lightkeeper#13]
https://github.com/kalaksi/lightkeeper/blob/8692eeaa6607d29aa1d5e098a58a6564ad89d9f4/src/frontend/qt/qml_frontend.rs#L103

I'm trying to create a Nix derivation of this but found that always is used in the file://, so manually the qml must be copied to result derivation. If these resources are already in a rc, why not use that rc?

**Comment by kalaksi** [comment]
No reason, really. It's just how it was done and I don't think they currently are included in the resources? `resources.rs` currently contains only images, but I'm open to suggestions.

**Comment by lfdominguez** [comment]
Thanks for response... I think that's better that you include all qml files inside the qrc.. so it's more reproducible in your app, not depending on copy of all qml files.

**Comment by kalaksi** [comment]
At least in flatpak's case, it shouldn't make it less reproducible since the qml files are from the same archive as the code. Having the qml files as resources would, AFAIK, in practice just include the qml in a different way (not as separate files). With the current setup, I don't need to manage them separately as resources when developing.

I see your point, though. It'd be easier in other ways to have them bundled as resources. Can you sensibly work around this for now? I'm currently working on other things like better NixOS support(!) and error handling improvements, but could work on this after those.

**Comment by lfdominguez** [comment]
Yes I can copy all the qml files to the result derivation... thanks

**Comment by kalaksi** [comment]
@lfdominguez FYI, 0.14.0 now has QML embedded as resources

**Comment by lfdominguez** [comment]
Thanksss
